theme: jekyll-theme-modernist

title: "Processing Networks"
description: >- # this means to ignore newlines until "baseurl:"
  Companion webpage to the book "Processing Networks: Fluid Models and Stability".
  Copyright 2019 by Jim Dai and J. Michael Harrison.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spnbook.com"
github_username: spnbook